export const CARD_CATEGORY = {
	NEWS: 'News',
	CLUB_INFO: 'Club Info',
	MERCH: 'Teamwear',
	EVENTS: 'Events',
	REGO: 'Registration Prices',
	CARNIVALS: 'Carnivals',
	RESOURCES: 'Resources',
	HISTORY: 'History',
	SEASON_INFO: 'Season Info',
	PLAYER_INFO: 'Player Info',
	COACHES: 'Coaches',
	COMMITTEE: 'Committee',
	LIFE_MEMBERS: 'Life Members',
	PLATINUM_SPONSORS: 'Platinum Sponsors',
	GOLD_SPONSORS: 'Gold Sponsors',
	SILVER_SPONSORS: 'Silver Sponsors',
	BRONZE_SPONSORS: 'Bronze Sponsors',
	DONATION_SPONSORS: 'Donations',
	GRANT_SPONSORS: 'Community Grants',
	IMPORTANT_DATES: 'Important Dates',
	FAIR_PLAY: 'Fair Play',
};

export const SPONSOR_TYPE = {
	PLATINUM: 'platinum',
	GOLD: 'gold',
	SILVER: 'silver',
	BRONZE: 'bronze',
	DONATION: 'donation',
	GRANT: 'grant',
};

export const SECTION_CATEGORY = {
	REGO_INFO: 'Registration Info',
	MINIROOS_INFO: 'Miniroos Info',
	JUNIORS_INFO: 'Juniors Info',
	SENIORS_INFO: 'Seniors Info',
	PLAYER_INFO: 'Player Info',
	COACH_INFO: 'Coach Info',
	FAIRPLAY_INFO: 'FairPlay Info',
	VOLUNTEER_INFO: 'Volunteer Info',
	COMMITTEE_INFO: 'Committee Info',
	LIFE_MEMBERS_INFO: 'Life Members Info',
	SPONSORS_INFO: 'Sponsors Info',
	HISTORY_INFO: 'History Info',
	CLUB_INFO: 'Club Info',
	BLUE_CARD_INFO: 'Blue Card Info',
};
